[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ElectroLab"
authors = [{name = "J.G.Aguado", email = "gjon-garcia@hotmail.com"}]
dynamic = ["version", "description"]
